server:
  port: 8005
spring:
  application:
    name: task
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
